### ISSUE TITLE
[Crash] Exception in server tick loop

### ISSUE THREAD

**Issue by dathide** [timinc-cobble/cobblemon-shiny-sparkles-1.5-fabric#1]
[crash-2024-06-04_12.30.50-server.txt](https://github.com/user-attachments/files/15569537/crash-2024-06-04_12.30.50-server.txt)

**Comment by tmetcalfe89** [comment]
Please post your latest.log, your crash log only gives so much information.

**Comment by dathide** [comment]
[latest.log](https://github.com/user-attachments/files/15569546/latest.log)

**Comment by dathide** [comment]
Also, thank you for making this mod

**Comment by tmetcalfe89** [comment]
Thanks for trying it out! Did you just kick up a new world with it and it gave you this issue?

**Comment by dathide** [comment]
No, I spent over 5 hours in the world before adding this mod.

**Comment by tmetcalfe89** [comment]
To be resolved in #2

**Comment by tmetcalfe89** [comment]
Should be resolved in v1.0.1.
